/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#2e7d32",
        "on-error": "#ffffff",
        "inverse-surface": "#263238",
        "surface-container-high": "#ddeaf2",
        "primary": "#0d631b",
        "on-tertiary-fixed-variant": "#004e59",
        "on-tertiary": "#ffffff",
        "secondary": "#ac3509",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#1b6d24",
        "secondary-fixed": "#ffdbd0",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#9eefff",
        "on-tertiary-container": "#d4f7ff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#3a0a00",
        "on-tertiary-fixed": "#001f24",
        "on-surface": "#111d23",
        "surface-bright": "#f4faff",
        "on-primary-fixed": "#002204",
        "tertiary-fixed-dim": "#55d7ed",
        "surface": "#f4faff",
        "surface-container": "#e3f0f8",
        "inverse-primary": "#88d982",
        "primary-fixed-dim": "#88d982",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#e6f3fb",
        "on-primary": "#ffffff",
        "surface-dim": "#cfdce4",
        "outline": "#707a6c",
        "tertiary-container": "#007988",
        "on-background": "#111d23",
        "on-primary-container": "#cbffc2",
        "outline-variant": "#bfcaba",
        "secondary-fixed-dim": "#ffb59f",
        "surface-container-highest": "#d7e4ec",
        "on-surface-variant": "#40493d",
        "surface-container-low": "#e9f6fd",
        "error-container": "#ffdad6",
        "surface-variant": "#d7e4ec",
        "on-primary-fixed-variant": "#005312",
        "primary-fixed": "#a3f69c",
        "on-secondary-container": "#631800",
        "secondary-container": "#fe6f42",
        "tertiary": "#005e6b",
        "background": "#f4faff",
        "on-secondary-fixed-variant": "#852300"
      },
      spacing: {
        "lg": "48px",
        "sm": "12px",
        "xs": "4px",
        "md": "24px",
        "base": "8px",
        "gutter": "24px",
        "container-max": "1280px",
        "xl": "80px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}